name: Template

configs:
  Release: release

options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    macOS: 11.0
    iOS: 15.0
  bundleIdPrefix: com.imthath.template.

attributes:
  ORGANIZATIONNAME: SkyDevz

targets:
  TemplateMac:
    type: application
    platform: macOS
    sources:
     - path: Shared
     - path: macOS
    configFiles:
      Release: Configs/Release.xcconfig
    postCompileScripts:
      - name: SwiftLint
        script: ./lint.sh
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID_PREFIX)$(SCHEME_NAME)
        PRODUCT_NAME: $(APP_NAME)
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        INFOPLIST_FILE: macOS/Info.plist
      Release:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Distribution"
  Template:
    type: application
    platform: iOS
    sources: 
      - path: Shared
      - path: iOS
    configFiles:
      Release: Configs/Release.xcconfig
    postCompileScripts:
      - name: SwiftLint
        script: ./lint.sh
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID_PREFIX)$(SCHEME_NAME)
        PRODUCT_NAME: $(APP_NAME)
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        INFOPLIST_FILE: iOS/Info.plist
      Release:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Distribution"
